Добавлен привязанный сервис для получения списка контактов и детальной информации о контакте
moroz1398/65apps-course pull request #3
Opened 2021-11-02 17:14 UTC by moroz1398

2021-11-02 17:21 UTC, moroz1398 commented
@nmodelov Я тут немного обмазался интерфейсами, не придумал как разрулить ситуацию, когда фрагмент уже создался, а сервис еще не приконнектился, отсюда и вылезли  ContactsServiceListener и ContactsServiceInterface...

Также добавил rxjava, для асинхронных запросов( все равно rx дальше по курсу будет), но пока не добавил presenter/VM, так как пока не знаю какая архитектура будет) Поэтому не пугайся от compositeDisposable во фрагменте)

2021-11-03 05:15 UTC, nmodelov commented
1. Оформление MR никто не отменял, каждый должен содержать описание того что было сделано, скрины, описание задачи.
2. начинай делать 4 ДЗ, для этого тебе сервисы не нужны, пока я буду проверять 3 ДЗ. Потом сделаешь ребейз, потренируешься.

позже проверю

2021-11-03 07:30 UTC, nmodelov requested changes

2021-11-03 07:30 UTC, nmodelov commented on app/src/main/java/com/gmail/moroz071398/ui/activities/MainActivity.kt
> +    private var contactsServiceBound = false
Переменные логического типа должны отвечать на вопрос, следовательно подставляется в начале глагол `is` или `has` и т.п.(в зависимости от контекста)

2021-11-03 07:30 UTC, nmodelov commented on app/src/main/java/com/gmail/moroz071398/ui/activities/MainActivity.kt
> +            val currentFragment = supportFragmentManager.findFragmentById(R.id.container)
WeakReferences<>

2021-11-03 07:30 UTC, nmodelov commented on app/src/main/java/com/gmail/moroz071398/service/contacts/ContactsService.kt
> +        Single.just(ContactsMockData.getContacts())
just вызывается на UI потоке, следовательно его блокирует. Когда у тебя там будет тяжелая операция, то приложение зависнет для пользователя, что плохо. Использовать можно `fromCallable`:
`Single.fromCallable { foo() }`

2021-11-03 07:30 UTC, nmodelov commented on app/src/main/java/com/gmail/moroz071398/ui/fragments/contact_details/ContactDetailsFragment.kt
> +        binding.detailContactEmails.text = contact?.emails?.joinToString("\n")
```
binding.apply {
detailContactName.text = contact?.name
        detailContactImage.loadFromUrl(contact?.imageUrl)
        detailContactDescription.text = contact?.description
       detailContactPhones.text = contact?.phones?.joinToString("\n")
        detailContactEmails.text = contact?.emails?.joinToString("\n")
}
```

2021-11-04 18:40 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/service/contacts/ContactsServiceInterface.kt
> +interface ContactsServiceInterface {
Да, накосячил, да и вообще. тут у меня сильно много интерфейсов получилось

2021-11-04 19:21 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/ui/activities/MainActivity.kt
> +            val currentFragment = supportFragmentManager.findFragmentById(R.id.container)
А зачем тут это нужно?)

2021-11-04 19:25 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/service/contacts/ContactsService.kt
> +        Single.just(ContactsMockData.getContacts())
Ага. точно, спасибо

2021-11-04 19:34 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/service/contacts/ContactsServiceInterface.kt
> +interface ContactsServiceInterface {
Исправил

2021-11-04 19:34 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/ui/activities/MainActivity.kt
> +    private var contactsServiceBound = false
Исправил

2021-11-04 19:34 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/ui/activities/MainActivity.kt
> +            val currentFragment = supportFragmentManager.findFragmentById(R.id.container)
Исправил

2021-11-04 19:35 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/service/contacts/ContactsService.kt
> +        Single.just(ContactsMockData.getContacts())
Исправил

2021-11-04 19:35 UTC, moroz1398 commented on app/src/main/java/com/gmail/moroz071398/ui/fragments/contact_details/ContactDetailsFragment.kt
> +        binding.detailContactEmails.text = contact?.emails?.joinToString("\n")
Исправил (пробежался по всем таким местам)

2021-11-07 10:07 UTC, merged